remote_theme: pmarsceill/just-the-docs
logo: "/images/logo.png"
aux_links:
  "Finastra Open API Sanboxes":
    - "https://fusionfabric.github.io/open-api-sandboxes/"
aux_links_new_tab: true
footer_content: "Copyright &copy; 2021 Finastra. Distributed by an <a href=\"https://github.com/fusionfabric/open-api-sandboxes/blob/main/LICENSE.md\">MIT license.</a>"
